#!/bin/bash

E_MC_INLCUDE_ARGSLIB=65
E_MC_INLCUDE_ARGSLIB_MSG="Impossibile includere argslib.sh"
E_MC_INLCUDE_LOGLIB=66
E_MC_INLCUDE_LOGLIB_MSG="Impossibile includere loglib.sh"

LOG_POSITION=$(basename $0)

# include argslib.sh
. ./bash/argslib.sh 2> /dev/null
[[ $? -gt 0 ]] && echo $E_MC_INLCUDE_ARGSLIB_MSG && exit $E_MC_INLCUDE_ARGSLIB

# include loglib.sh
. ./bash/loglib.sh 2> /dev/null
[[ $? -gt 0 ]] && echo $E_MC_INLCUDE_LOGLIB_MSG && exit $E_MC_INLCUDE_LOGLIB

G_UCLIENT_NAME="uclient/get-uclient"
G_LOGPOS=$(basename $0)

bt_info "touch $G_UCLIENT_NAME" "touch $G_UCLIENT_NAME" $G_LOGPOS

bt_info_up "write headers to $G_UCLIENT_NAME" $G_LOGPOS
echo '#!/bin/bash' > $G_UCLIENT_NAME 2> /dev/null
bt_info_down $BT_TYPE_EQ_ZERO $? 

bt_info_up "write argslib.sh to $G_UCLIENT_NAME" $G_LOGPOS
cat ./bash/argslib.sh >> $G_UCLIENT_NAME 2> /dev/null
bt_info_down $BT_TYPE_EQ_ZERO $? 

bt_info_up "write loglib.sh to $G_UCLIENT_NAME" $G_LOGPOS
cat ./bash/loglib.sh >> $G_UCLIENT_NAME 2> /dev/null
bt_info_down $BT_TYPE_EQ_ZERO $? 

bt_info_up "write download-microclient code to $G_UCLIENT_NAME" $G_LOGPOS
cat ./download-microclient >> $G_UCLIENT_NAME 2> /dev/null
bt_info_down $BT_TYPE_EQ_ZERO $? 

bt_info "chmod +x $G_UCLIENT_NAME" "set permission to +x for $G_UCLIENT_NAME" $G_LOGPOS

